### ISSUE TITLE
MIT License violation

### ISSUE THREAD

**Issue by tshemsedinov** [pro100taA/infrastructure#1]
Please reread MIT license terms and respect its conditions: "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software." here is translation: https://ru.wikipedia.org/wiki/Лицензия_MIT
You can't remove any line from this file: https://github.com/metarhia/config/blob/master/LICENSE only add your additional copyrights.

**Comment by pro100taA** [comment]
Done.

**Comment by tshemsedinov** [comment]
You need to add your copyrights in LICENSE file too
